//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace ConsultaHistDetec.seg {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SegurancaWSSoap", Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataTransferObject))]
    public partial class SegurancaWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RetornarConcedenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarSenhaPosicionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback SalvarOuAlterarConcedenteOperationCompleted;
        
        private HeaderAutenticacao headerAutenticacaoValueField;
        
        private System.Threading.SendOrPostCallback ValidarAcessoAoSistemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarDataLimiteDeUsoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LiberarLicencaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback SalvarOuAlterarUsuarioGlobusOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarUsuariosSelecionadosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SegurancaWS() {
            this.Url = global::ConsultaHistDetec.Properties.Settings.Default.ConsultaHistDetec_seg_SegurancaWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public HeaderAutenticacao HeaderAutenticacaoValue {
            get {
                return this.headerAutenticacaoValueField;
            }
            set {
                this.headerAutenticacaoValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RetornarConcedenteCompletedEventHandler RetornarConcedenteCompleted;
        
        /// <remarks/>
        public event LogarUsuarioCompletedEventHandler LogarUsuarioCompleted;
        
        /// <remarks/>
        public event RetornarSenhaPosicionalCompletedEventHandler RetornarSenhaPosicionalCompleted;
        
        /// <remarks/>
        public event SalvarOuAlterarConcedenteCompletedEventHandler SalvarOuAlterarConcedenteCompleted;
        
        /// <remarks/>
        public event ValidarAcessoAoSistemaCompletedEventHandler ValidarAcessoAoSistemaCompleted;
        
        /// <remarks/>
        public event VerificarDataLimiteDeUsoCompletedEventHandler VerificarDataLimiteDeUsoCompleted;
        
        /// <remarks/>
        public event LiberarLicencaCompletedEventHandler LiberarLicencaCompleted;
        
        /// <remarks/>
        public event RetornarUsuariosCompletedEventHandler RetornarUsuariosCompleted;
        
        /// <remarks/>
        public event RetornarUsuarioCompletedEventHandler RetornarUsuarioCompleted;
        
        /// <remarks/>
        public event SalvarOuAlterarUsuarioGlobusCompletedEventHandler SalvarOuAlterarUsuarioGlobusCompleted;
        
        /// <remarks/>
        public event RetornarUsuariosSelecionadosCompletedEventHandler RetornarUsuariosSelecionadosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/RetornarConcedente", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConcedenteDTO RetornarConcedente() {
            object[] results = this.Invoke("RetornarConcedente", new object[0]);
            return ((ConcedenteDTO)(results[0]));
        }
        
        /// <remarks/>
        public void RetornarConcedenteAsync() {
            this.RetornarConcedenteAsync(null);
        }
        
        /// <remarks/>
        public void RetornarConcedenteAsync(object userState) {
            if ((this.RetornarConcedenteOperationCompleted == null)) {
                this.RetornarConcedenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarConcedenteOperationCompleted);
            }
            this.InvokeAsync("RetornarConcedente", new object[0], this.RetornarConcedenteOperationCompleted, userState);
        }
        
        private void OnRetornarConcedenteOperationCompleted(object arg) {
            if ((this.RetornarConcedenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarConcedenteCompleted(this, new RetornarConcedenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/LogarUsuario", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LogarUsuario(string usuario, string senha, string sistema, string usuarioSac) {
            this.Invoke("LogarUsuario", new object[] {
                        usuario,
                        senha,
                        sistema,
                        usuarioSac});
        }
        
        /// <remarks/>
        public void LogarUsuarioAsync(string usuario, string senha, string sistema, string usuarioSac) {
            this.LogarUsuarioAsync(usuario, senha, sistema, usuarioSac, null);
        }
        
        /// <remarks/>
        public void LogarUsuarioAsync(string usuario, string senha, string sistema, string usuarioSac, object userState) {
            if ((this.LogarUsuarioOperationCompleted == null)) {
                this.LogarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogarUsuarioOperationCompleted);
            }
            this.InvokeAsync("LogarUsuario", new object[] {
                        usuario,
                        senha,
                        sistema,
                        usuarioSac}, this.LogarUsuarioOperationCompleted, userState);
        }
        
        private void OnLogarUsuarioOperationCompleted(object arg) {
            if ((this.LogarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/RetornarSenhaPosicional", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RetornarSenhaPosicional() {
            object[] results = this.Invoke("RetornarSenhaPosicional", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RetornarSenhaPosicionalAsync() {
            this.RetornarSenhaPosicionalAsync(null);
        }
        
        /// <remarks/>
        public void RetornarSenhaPosicionalAsync(object userState) {
            if ((this.RetornarSenhaPosicionalOperationCompleted == null)) {
                this.RetornarSenhaPosicionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarSenhaPosicionalOperationCompleted);
            }
            this.InvokeAsync("RetornarSenhaPosicional", new object[0], this.RetornarSenhaPosicionalOperationCompleted, userState);
        }
        
        private void OnRetornarSenhaPosicionalOperationCompleted(object arg) {
            if ((this.RetornarSenhaPosicionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarSenhaPosicionalCompleted(this, new RetornarSenhaPosicionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/SalvarOuAlterarConcedente", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SalvarOuAlterarConcedente(ConcedenteDTO concedenteDTO) {
            this.Invoke("SalvarOuAlterarConcedente", new object[] {
                        concedenteDTO});
        }
        
        /// <remarks/>
        public void SalvarOuAlterarConcedenteAsync(ConcedenteDTO concedenteDTO) {
            this.SalvarOuAlterarConcedenteAsync(concedenteDTO, null);
        }
        
        /// <remarks/>
        public void SalvarOuAlterarConcedenteAsync(ConcedenteDTO concedenteDTO, object userState) {
            if ((this.SalvarOuAlterarConcedenteOperationCompleted == null)) {
                this.SalvarOuAlterarConcedenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalvarOuAlterarConcedenteOperationCompleted);
            }
            this.InvokeAsync("SalvarOuAlterarConcedente", new object[] {
                        concedenteDTO}, this.SalvarOuAlterarConcedenteOperationCompleted, userState);
        }
        
        private void OnSalvarOuAlterarConcedenteOperationCompleted(object arg) {
            if ((this.SalvarOuAlterarConcedenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalvarOuAlterarConcedenteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderAutenticacaoValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/ValidarAcessoAoSistema", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConcedenteDTO ValidarAcessoAoSistema(string aplicacao, string estacao, string sistema, string usuarioSO, bool consomeLicenca) {
            object[] results = this.Invoke("ValidarAcessoAoSistema", new object[] {
                        aplicacao,
                        estacao,
                        sistema,
                        usuarioSO,
                        consomeLicenca});
            return ((ConcedenteDTO)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarAcessoAoSistemaAsync(string aplicacao, string estacao, string sistema, string usuarioSO, bool consomeLicenca) {
            this.ValidarAcessoAoSistemaAsync(aplicacao, estacao, sistema, usuarioSO, consomeLicenca, null);
        }
        
        /// <remarks/>
        public void ValidarAcessoAoSistemaAsync(string aplicacao, string estacao, string sistema, string usuarioSO, bool consomeLicenca, object userState) {
            if ((this.ValidarAcessoAoSistemaOperationCompleted == null)) {
                this.ValidarAcessoAoSistemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarAcessoAoSistemaOperationCompleted);
            }
            this.InvokeAsync("ValidarAcessoAoSistema", new object[] {
                        aplicacao,
                        estacao,
                        sistema,
                        usuarioSO,
                        consomeLicenca}, this.ValidarAcessoAoSistemaOperationCompleted, userState);
        }
        
        private void OnValidarAcessoAoSistemaOperationCompleted(object arg) {
            if ((this.ValidarAcessoAoSistemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarAcessoAoSistemaCompleted(this, new ValidarAcessoAoSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/VerificarDataLimiteDeUso", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerificarDataLimiteDeUso(string sistema) {
            object[] results = this.Invoke("VerificarDataLimiteDeUso", new object[] {
                        sistema});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarDataLimiteDeUsoAsync(string sistema) {
            this.VerificarDataLimiteDeUsoAsync(sistema, null);
        }
        
        /// <remarks/>
        public void VerificarDataLimiteDeUsoAsync(string sistema, object userState) {
            if ((this.VerificarDataLimiteDeUsoOperationCompleted == null)) {
                this.VerificarDataLimiteDeUsoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarDataLimiteDeUsoOperationCompleted);
            }
            this.InvokeAsync("VerificarDataLimiteDeUso", new object[] {
                        sistema}, this.VerificarDataLimiteDeUsoOperationCompleted, userState);
        }
        
        private void OnVerificarDataLimiteDeUsoOperationCompleted(object arg) {
            if ((this.VerificarDataLimiteDeUsoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarDataLimiteDeUsoCompleted(this, new VerificarDataLimiteDeUsoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/LiberarLicenca", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LiberarLicenca(string estacao, string sistema, string usuarioSO) {
            this.Invoke("LiberarLicenca", new object[] {
                        estacao,
                        sistema,
                        usuarioSO});
        }
        
        /// <remarks/>
        public void LiberarLicencaAsync(string estacao, string sistema, string usuarioSO) {
            this.LiberarLicencaAsync(estacao, sistema, usuarioSO, null);
        }
        
        /// <remarks/>
        public void LiberarLicencaAsync(string estacao, string sistema, string usuarioSO, object userState) {
            if ((this.LiberarLicencaOperationCompleted == null)) {
                this.LiberarLicencaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLiberarLicencaOperationCompleted);
            }
            this.InvokeAsync("LiberarLicenca", new object[] {
                        estacao,
                        sistema,
                        usuarioSO}, this.LiberarLicencaOperationCompleted, userState);
        }
        
        private void OnLiberarLicencaOperationCompleted(object arg) {
            if ((this.LiberarLicencaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LiberarLicencaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/RetornarUsuarios", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioDTO[] RetornarUsuarios() {
            object[] results = this.Invoke("RetornarUsuarios", new object[0]);
            return ((UsuarioDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornarUsuariosAsync() {
            this.RetornarUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void RetornarUsuariosAsync(object userState) {
            if ((this.RetornarUsuariosOperationCompleted == null)) {
                this.RetornarUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarUsuariosOperationCompleted);
            }
            this.InvokeAsync("RetornarUsuarios", new object[0], this.RetornarUsuariosOperationCompleted, userState);
        }
        
        private void OnRetornarUsuariosOperationCompleted(object arg) {
            if ((this.RetornarUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarUsuariosCompleted(this, new RetornarUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/RetornarUsuario", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioDTO RetornarUsuario(string usuario) {
            object[] results = this.Invoke("RetornarUsuario", new object[] {
                        usuario});
            return ((UsuarioDTO)(results[0]));
        }
        
        /// <remarks/>
        public void RetornarUsuarioAsync(string usuario) {
            this.RetornarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void RetornarUsuarioAsync(string usuario, object userState) {
            if ((this.RetornarUsuarioOperationCompleted == null)) {
                this.RetornarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarUsuarioOperationCompleted);
            }
            this.InvokeAsync("RetornarUsuario", new object[] {
                        usuario}, this.RetornarUsuarioOperationCompleted, userState);
        }
        
        private void OnRetornarUsuarioOperationCompleted(object arg) {
            if ((this.RetornarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarUsuarioCompleted(this, new RetornarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/SalvarOuAlterarUsuarioGlobus", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SalvarOuAlterarUsuarioGlobus(UsuarioDTO usuarioDTO) {
            this.Invoke("SalvarOuAlterarUsuarioGlobus", new object[] {
                        usuarioDTO});
        }
        
        /// <remarks/>
        public void SalvarOuAlterarUsuarioGlobusAsync(UsuarioDTO usuarioDTO) {
            this.SalvarOuAlterarUsuarioGlobusAsync(usuarioDTO, null);
        }
        
        /// <remarks/>
        public void SalvarOuAlterarUsuarioGlobusAsync(UsuarioDTO usuarioDTO, object userState) {
            if ((this.SalvarOuAlterarUsuarioGlobusOperationCompleted == null)) {
                this.SalvarOuAlterarUsuarioGlobusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalvarOuAlterarUsuarioGlobusOperationCompleted);
            }
            this.InvokeAsync("SalvarOuAlterarUsuarioGlobus", new object[] {
                        usuarioDTO}, this.SalvarOuAlterarUsuarioGlobusOperationCompleted, userState);
        }
        
        private void OnSalvarOuAlterarUsuarioGlobusOperationCompleted(object arg) {
            if ((this.SalvarOuAlterarUsuarioGlobusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalvarOuAlterarUsuarioGlobusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/fglobus/seguranca/RetornarUsuariosSelecionados", RequestNamespace="http://bgmrodotec.com.br/fglobus/seguranca", ResponseNamespace="http://bgmrodotec.com.br/fglobus/seguranca", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioDTO[] RetornarUsuariosSelecionados(string[] usuario) {
            object[] results = this.Invoke("RetornarUsuariosSelecionados", new object[] {
                        usuario});
            return ((UsuarioDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornarUsuariosSelecionadosAsync(string[] usuario) {
            this.RetornarUsuariosSelecionadosAsync(usuario, null);
        }
        
        /// <remarks/>
        public void RetornarUsuariosSelecionadosAsync(string[] usuario, object userState) {
            if ((this.RetornarUsuariosSelecionadosOperationCompleted == null)) {
                this.RetornarUsuariosSelecionadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarUsuariosSelecionadosOperationCompleted);
            }
            this.InvokeAsync("RetornarUsuariosSelecionados", new object[] {
                        usuario}, this.RetornarUsuariosSelecionadosOperationCompleted, userState);
        }
        
        private void OnRetornarUsuariosSelecionadosOperationCompleted(object arg) {
            if ((this.RetornarUsuariosSelecionadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarUsuariosSelecionadosCompleted(this, new RetornarUsuariosSelecionadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca", IsNullable=false)]
    public partial class HeaderAutenticacao : System.Web.Services.Protocols.SoapHeader {
        
        private string valorChaveCRUDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string ValorChaveCRUD {
            get {
                return this.valorChaveCRUDField;
            }
            set {
                this.valorChaveCRUDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AutorizacaoDoSistemaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SistemaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumoDeLicencaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LicencaExclusivaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LicencaGeralDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParametroControleDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusDeAtualizacaoDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UsuarioDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConcedenteDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    public abstract partial class DataTransferObject {
        
        private bool achouRegistroField;
        
        /// <remarks/>
        public bool AchouRegistro {
            get {
                return this.achouRegistroField;
            }
            set {
                this.achouRegistroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    public partial class AutorizacaoDoSistemaDTO : DataTransferObject {
        
        private int codIntEmpAutField;
        
        private string sistemaField;
        
        private System.DateTime dataLimiteDeUsoField;
        
        private string checkSumAutSistemasField;
        
        private SistemaDTO sistemaOBJField;
        
        /// <remarks/>
        public int CodIntEmpAut {
            get {
                return this.codIntEmpAutField;
            }
            set {
                this.codIntEmpAutField = value;
            }
        }
        
        /// <remarks/>
        public string Sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataLimiteDeUso {
            get {
                return this.dataLimiteDeUsoField;
            }
            set {
                this.dataLimiteDeUsoField = value;
            }
        }
        
        /// <remarks/>
        public string CheckSumAutSistemas {
            get {
                return this.checkSumAutSistemasField;
            }
            set {
                this.checkSumAutSistemasField = value;
            }
        }
        
        /// <remarks/>
        public SistemaDTO SistemaOBJ {
            get {
                return this.sistemaOBJField;
            }
            set {
                this.sistemaOBJField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    public partial class SistemaDTO : DataTransferObject {
        
        private string sistemaField;
        
        private string nomeDoSistemaField;
        
        private string descricaoDoSistemaField;
        
        private string dataHoraMenusField;
        
        /// <remarks/>
        public string Sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <remarks/>
        public string NomeDoSistema {
            get {
                return this.nomeDoSistemaField;
            }
            set {
                this.nomeDoSistemaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoDoSistema {
            get {
                return this.descricaoDoSistemaField;
            }
            set {
                this.descricaoDoSistemaField = value;
            }
        }
        
        /// <remarks/>
        public string DataHoraMenus {
            get {
                return this.dataHoraMenusField;
            }
            set {
                this.dataHoraMenusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    public partial class ConsumoDeLicencaDTO : DataTransferObject {
        
        private string aplicacaoField;
        
        private string estacaoField;
        
        private System.DateTime dataHoraField;
        
        private string usuarioWinField;
        
        private string usuarioGlobusField;
        
        private string sistemaField;
        
        private System.DateTime validaSessaoField;
        
        /// <remarks/>
        public string Aplicacao {
            get {
                return this.aplicacaoField;
            }
            set {
                this.aplicacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Estacao {
            get {
                return this.estacaoField;
            }
            set {
                this.estacaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataHora {
            get {
                return this.dataHoraField;
            }
            set {
                this.dataHoraField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioWin {
            get {
                return this.usuarioWinField;
            }
            set {
                this.usuarioWinField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioGlobus {
            get {
                return this.usuarioGlobusField;
            }
            set {
                this.usuarioGlobusField = value;
            }
        }
        
        /// <remarks/>
        public string Sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidaSessao {
            get {
                return this.validaSessaoField;
            }
            set {
                this.validaSessaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    public partial class LicencaExclusivaDTO : DataTransferObject {
        
        private string sistemaField;
        
        private int qtdeAcessoField;
        
        private string checksumAcessoField;
        
        /// <remarks/>
        public string Sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <remarks/>
        public int QtdeAcesso {
            get {
                return this.qtdeAcessoField;
            }
            set {
                this.qtdeAcessoField = value;
            }
        }
        
        /// <remarks/>
        public string ChecksumAcesso {
            get {
                return this.checksumAcessoField;
            }
            set {
                this.checksumAcessoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    public partial class LicencaGeralDTO : DataTransferObject {
        
        private int codIntConcedenteField;
        
        private int qtdeTotalField;
        
        private string checksumAcTotField;
        
        /// <remarks/>
        public int CodIntConcedente {
            get {
                return this.codIntConcedenteField;
            }
            set {
                this.codIntConcedenteField = value;
            }
        }
        
        /// <remarks/>
        public int QtdeTotal {
            get {
                return this.qtdeTotalField;
            }
            set {
                this.qtdeTotalField = value;
            }
        }
        
        /// <remarks/>
        public string ChecksumAcTot {
            get {
                return this.checksumAcTotField;
            }
            set {
                this.checksumAcTotField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    public partial class ParametroControleDTO : DataTransferObject {
        
        private string codigoCadAutomaticoField;
        
        private string usarPortuguesPadraoField;
        
        private string senhaPosicionalField;
        
        /// <remarks/>
        public string CodigoCadAutomatico {
            get {
                return this.codigoCadAutomaticoField;
            }
            set {
                this.codigoCadAutomaticoField = value;
            }
        }
        
        /// <remarks/>
        public string UsarPortuguesPadrao {
            get {
                return this.usarPortuguesPadraoField;
            }
            set {
                this.usarPortuguesPadraoField = value;
            }
        }
        
        /// <remarks/>
        public string SenhaPosicional {
            get {
                return this.senhaPosicionalField;
            }
            set {
                this.senhaPosicionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    public partial class StatusDeAtualizacaoDTO : DataTransferObject {
        
        private int nRegField;
        
        private string winLoginField;
        
        /// <remarks/>
        public int NReg {
            get {
                return this.nRegField;
            }
            set {
                this.nRegField = value;
            }
        }
        
        /// <remarks/>
        public string WinLogin {
            get {
                return this.winLoginField;
            }
            set {
                this.winLoginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    public partial class UsuarioDTO : DataTransferObject {
        
        private string usuarioField;
        
        private string nomeUsuarioField;
        
        private System.Nullable<int> codigoGrpUsuField;
        
        private string senhaField;
        
        private string senhaTrVelocUsuField;
        
        private string senhaTrCatraUsuField;
        
        private System.Nullable<int> codIntFuncField;
        
        private System.DateTime dataSenhaField;
        
        private string ativoField;
        
        private string loginSnapField;
        
        private string senhaSnapField;
        
        private string portaEnvioField;
        
        private string servidorSmtpField;
        
        private string emailField;
        
        private string portaPop3Field;
        
        private string administradorField;
        
        private string acessaTodasOpcoesField;
        
        private string usuarioDBField;
        
        private string senhaDBField;
        
        private string digitaMotManField;
        
        private string digitaLinhaManField;
        
        private string excluiOsExecServManField;
        
        private string flgArrecadacaoField;
        
        private string codigoAux1Field;
        
        private string senhaWebField;
        
        private string nrInscrWebField;
        
        private string servidorPop3Field;
        
        private System.Nullable<int> acessoGlbReportField;
        
        private string flgCargasField;
        
        private bool trocaSenhaField;
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string NomeUsuario {
            get {
                return this.nomeUsuarioField;
            }
            set {
                this.nomeUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CodigoGrpUsu {
            get {
                return this.codigoGrpUsuField;
            }
            set {
                this.codigoGrpUsuField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public string SenhaTrVelocUsu {
            get {
                return this.senhaTrVelocUsuField;
            }
            set {
                this.senhaTrVelocUsuField = value;
            }
        }
        
        /// <remarks/>
        public string SenhaTrCatraUsu {
            get {
                return this.senhaTrCatraUsuField;
            }
            set {
                this.senhaTrCatraUsuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CodIntFunc {
            get {
                return this.codIntFuncField;
            }
            set {
                this.codIntFuncField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataSenha {
            get {
                return this.dataSenhaField;
            }
            set {
                this.dataSenhaField = value;
            }
        }
        
        /// <remarks/>
        public string Ativo {
            get {
                return this.ativoField;
            }
            set {
                this.ativoField = value;
            }
        }
        
        /// <remarks/>
        public string LoginSnap {
            get {
                return this.loginSnapField;
            }
            set {
                this.loginSnapField = value;
            }
        }
        
        /// <remarks/>
        public string SenhaSnap {
            get {
                return this.senhaSnapField;
            }
            set {
                this.senhaSnapField = value;
            }
        }
        
        /// <remarks/>
        public string PortaEnvio {
            get {
                return this.portaEnvioField;
            }
            set {
                this.portaEnvioField = value;
            }
        }
        
        /// <remarks/>
        public string ServidorSmtp {
            get {
                return this.servidorSmtpField;
            }
            set {
                this.servidorSmtpField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string PortaPop3 {
            get {
                return this.portaPop3Field;
            }
            set {
                this.portaPop3Field = value;
            }
        }
        
        /// <remarks/>
        public string Administrador {
            get {
                return this.administradorField;
            }
            set {
                this.administradorField = value;
            }
        }
        
        /// <remarks/>
        public string AcessaTodasOpcoes {
            get {
                return this.acessaTodasOpcoesField;
            }
            set {
                this.acessaTodasOpcoesField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioDB {
            get {
                return this.usuarioDBField;
            }
            set {
                this.usuarioDBField = value;
            }
        }
        
        /// <remarks/>
        public string SenhaDB {
            get {
                return this.senhaDBField;
            }
            set {
                this.senhaDBField = value;
            }
        }
        
        /// <remarks/>
        public string DigitaMotMan {
            get {
                return this.digitaMotManField;
            }
            set {
                this.digitaMotManField = value;
            }
        }
        
        /// <remarks/>
        public string DigitaLinhaMan {
            get {
                return this.digitaLinhaManField;
            }
            set {
                this.digitaLinhaManField = value;
            }
        }
        
        /// <remarks/>
        public string ExcluiOsExecServMan {
            get {
                return this.excluiOsExecServManField;
            }
            set {
                this.excluiOsExecServManField = value;
            }
        }
        
        /// <remarks/>
        public string FlgArrecadacao {
            get {
                return this.flgArrecadacaoField;
            }
            set {
                this.flgArrecadacaoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoAux1 {
            get {
                return this.codigoAux1Field;
            }
            set {
                this.codigoAux1Field = value;
            }
        }
        
        /// <remarks/>
        public string SenhaWeb {
            get {
                return this.senhaWebField;
            }
            set {
                this.senhaWebField = value;
            }
        }
        
        /// <remarks/>
        public string NrInscrWeb {
            get {
                return this.nrInscrWebField;
            }
            set {
                this.nrInscrWebField = value;
            }
        }
        
        /// <remarks/>
        public string ServidorPop3 {
            get {
                return this.servidorPop3Field;
            }
            set {
                this.servidorPop3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AcessoGlbReport {
            get {
                return this.acessoGlbReportField;
            }
            set {
                this.acessoGlbReportField = value;
            }
        }
        
        /// <remarks/>
        public string FlgCargas {
            get {
                return this.flgCargasField;
            }
            set {
                this.flgCargasField = value;
            }
        }
        
        /// <remarks/>
        public bool TrocaSenha {
            get {
                return this.trocaSenhaField;
            }
            set {
                this.trocaSenhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/fglobus/seguranca")]
    public partial class ConcedenteDTO : DataTransferObject {
        
        private int codIntConcedenteField;
        
        private string checksumConcedenteField;
        
        private string nomeConcedenteField;
        
        private System.Nullable<int> codigoClienteField;
        
        private string chaveClienteField;
        
        /// <remarks/>
        public int CodIntConcedente {
            get {
                return this.codIntConcedenteField;
            }
            set {
                this.codIntConcedenteField = value;
            }
        }
        
        /// <remarks/>
        public string ChecksumConcedente {
            get {
                return this.checksumConcedenteField;
            }
            set {
                this.checksumConcedenteField = value;
            }
        }
        
        /// <remarks/>
        public string NomeConcedente {
            get {
                return this.nomeConcedenteField;
            }
            set {
                this.nomeConcedenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CodigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
            }
        }
        
        /// <remarks/>
        public string ChaveCliente {
            get {
                return this.chaveClienteField;
            }
            set {
                this.chaveClienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RetornarConcedenteCompletedEventHandler(object sender, RetornarConcedenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarConcedenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarConcedenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConcedenteDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConcedenteDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LogarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RetornarSenhaPosicionalCompletedEventHandler(object sender, RetornarSenhaPosicionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarSenhaPosicionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarSenhaPosicionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SalvarOuAlterarConcedenteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ValidarAcessoAoSistemaCompletedEventHandler(object sender, ValidarAcessoAoSistemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarAcessoAoSistemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarAcessoAoSistemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConcedenteDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConcedenteDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VerificarDataLimiteDeUsoCompletedEventHandler(object sender, VerificarDataLimiteDeUsoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarDataLimiteDeUsoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarDataLimiteDeUsoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LiberarLicencaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RetornarUsuariosCompletedEventHandler(object sender, RetornarUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RetornarUsuarioCompletedEventHandler(object sender, RetornarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SalvarOuAlterarUsuarioGlobusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RetornarUsuariosSelecionadosCompletedEventHandler(object sender, RetornarUsuariosSelecionadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarUsuariosSelecionadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarUsuariosSelecionadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioDTO[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591