//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4200.
// 
#pragma warning disable 1591

namespace AppTesteHuman.IntegracaoWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IntegracaoWSSoap", Namespace="http://bgmrodotec.com.br/globus5/globus")]
    public partial class IntegracaoWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SalvarOuAlterarListaTabelaIntegradoraOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarMensagensProDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SalvarMensagensProDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarVeiculosQueVaoChegarNoLocalDaLinhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarVeiculosQueVaoChegarNoLocalOperationCompleted;
        
        private System.Threading.SendOrPostCallback SalvarRecebimentoSMSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IntegracaoWS() {
            this.Url = global::AppTesteHuman.Properties.Settings.Default.AppTesteHuman_IntegracaoWS_IntegracaoWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SalvarOuAlterarListaTabelaIntegradoraCompletedEventHandler SalvarOuAlterarListaTabelaIntegradoraCompleted;
        
        /// <remarks/>
        public event RetornarMensagensProDataCompletedEventHandler RetornarMensagensProDataCompleted;
        
        /// <remarks/>
        public event SalvarMensagensProDataCompletedEventHandler SalvarMensagensProDataCompleted;
        
        /// <remarks/>
        public event RetornarVeiculosQueVaoChegarNoLocalDaLinhaCompletedEventHandler RetornarVeiculosQueVaoChegarNoLocalDaLinhaCompleted;
        
        /// <remarks/>
        public event RetornarVeiculosQueVaoChegarNoLocalCompletedEventHandler RetornarVeiculosQueVaoChegarNoLocalCompleted;
        
        /// <remarks/>
        public event SalvarRecebimentoSMSCompletedEventHandler SalvarRecebimentoSMSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/globus5/globus/SalvarOuAlterarListaTabelaIntegradora", RequestNamespace="http://bgmrodotec.com.br/globus5/globus", ResponseNamespace="http://bgmrodotec.com.br/globus5/globus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SalvarOuAlterarListaTabelaIntegradora([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] sTabelaIntegradora[] sTabelaIntegradora) {
            object[] results = this.Invoke("SalvarOuAlterarListaTabelaIntegradora", new object[] {
                        sTabelaIntegradora});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SalvarOuAlterarListaTabelaIntegradoraAsync(sTabelaIntegradora[] sTabelaIntegradora) {
            this.SalvarOuAlterarListaTabelaIntegradoraAsync(sTabelaIntegradora, null);
        }
        
        /// <remarks/>
        public void SalvarOuAlterarListaTabelaIntegradoraAsync(sTabelaIntegradora[] sTabelaIntegradora, object userState) {
            if ((this.SalvarOuAlterarListaTabelaIntegradoraOperationCompleted == null)) {
                this.SalvarOuAlterarListaTabelaIntegradoraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalvarOuAlterarListaTabelaIntegradoraOperationCompleted);
            }
            this.InvokeAsync("SalvarOuAlterarListaTabelaIntegradora", new object[] {
                        sTabelaIntegradora}, this.SalvarOuAlterarListaTabelaIntegradoraOperationCompleted, userState);
        }
        
        private void OnSalvarOuAlterarListaTabelaIntegradoraOperationCompleted(object arg) {
            if ((this.SalvarOuAlterarListaTabelaIntegradoraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalvarOuAlterarListaTabelaIntegradoraCompleted(this, new SalvarOuAlterarListaTabelaIntegradoraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/globus5/globus/RetornarMensagensProData", RequestNamespace="http://bgmrodotec.com.br/globus5/globus", ResponseNamespace="http://bgmrodotec.com.br/globus5/globus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public sMensagens[] RetornarMensagensProData() {
            object[] results = this.Invoke("RetornarMensagensProData", new object[0]);
            return ((sMensagens[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornarMensagensProDataAsync() {
            this.RetornarMensagensProDataAsync(null);
        }
        
        /// <remarks/>
        public void RetornarMensagensProDataAsync(object userState) {
            if ((this.RetornarMensagensProDataOperationCompleted == null)) {
                this.RetornarMensagensProDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarMensagensProDataOperationCompleted);
            }
            this.InvokeAsync("RetornarMensagensProData", new object[0], this.RetornarMensagensProDataOperationCompleted, userState);
        }
        
        private void OnRetornarMensagensProDataOperationCompleted(object arg) {
            if ((this.RetornarMensagensProDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarMensagensProDataCompleted(this, new RetornarMensagensProDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/globus5/globus/SalvarMensagensProData", RequestNamespace="http://bgmrodotec.com.br/globus5/globus", ResponseNamespace="http://bgmrodotec.com.br/globus5/globus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SalvarMensagensProData([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] sMensagens[] mensagens) {
            this.Invoke("SalvarMensagensProData", new object[] {
                        mensagens});
        }
        
        /// <remarks/>
        public void SalvarMensagensProDataAsync(sMensagens[] mensagens) {
            this.SalvarMensagensProDataAsync(mensagens, null);
        }
        
        /// <remarks/>
        public void SalvarMensagensProDataAsync(sMensagens[] mensagens, object userState) {
            if ((this.SalvarMensagensProDataOperationCompleted == null)) {
                this.SalvarMensagensProDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalvarMensagensProDataOperationCompleted);
            }
            this.InvokeAsync("SalvarMensagensProData", new object[] {
                        mensagens}, this.SalvarMensagensProDataOperationCompleted, userState);
        }
        
        private void OnSalvarMensagensProDataOperationCompleted(object arg) {
            if ((this.SalvarMensagensProDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalvarMensagensProDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/globus5/globus/RetornarVeiculosQueVaoChegarNoLocalDaLinh" +
            "a", RequestNamespace="http://bgmrodotec.com.br/globus5/globus", ResponseNamespace="http://bgmrodotec.com.br/globus5/globus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public sRetornoSMS[] RetornarVeiculosQueVaoChegarNoLocalDaLinha(int codLocalidade, string codigoLinha) {
            object[] results = this.Invoke("RetornarVeiculosQueVaoChegarNoLocalDaLinha", new object[] {
                        codLocalidade,
                        codigoLinha});
            return ((sRetornoSMS[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornarVeiculosQueVaoChegarNoLocalDaLinhaAsync(int codLocalidade, string codigoLinha) {
            this.RetornarVeiculosQueVaoChegarNoLocalDaLinhaAsync(codLocalidade, codigoLinha, null);
        }
        
        /// <remarks/>
        public void RetornarVeiculosQueVaoChegarNoLocalDaLinhaAsync(int codLocalidade, string codigoLinha, object userState) {
            if ((this.RetornarVeiculosQueVaoChegarNoLocalDaLinhaOperationCompleted == null)) {
                this.RetornarVeiculosQueVaoChegarNoLocalDaLinhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarVeiculosQueVaoChegarNoLocalDaLinhaOperationCompleted);
            }
            this.InvokeAsync("RetornarVeiculosQueVaoChegarNoLocalDaLinha", new object[] {
                        codLocalidade,
                        codigoLinha}, this.RetornarVeiculosQueVaoChegarNoLocalDaLinhaOperationCompleted, userState);
        }
        
        private void OnRetornarVeiculosQueVaoChegarNoLocalDaLinhaOperationCompleted(object arg) {
            if ((this.RetornarVeiculosQueVaoChegarNoLocalDaLinhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarVeiculosQueVaoChegarNoLocalDaLinhaCompleted(this, new RetornarVeiculosQueVaoChegarNoLocalDaLinhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/globus5/globus/RetornarVeiculosQueVaoChegarNoLocal", RequestNamespace="http://bgmrodotec.com.br/globus5/globus", ResponseNamespace="http://bgmrodotec.com.br/globus5/globus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public sRetornoSMS[] RetornarVeiculosQueVaoChegarNoLocal(int codLocalidade) {
            object[] results = this.Invoke("RetornarVeiculosQueVaoChegarNoLocal", new object[] {
                        codLocalidade});
            return ((sRetornoSMS[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornarVeiculosQueVaoChegarNoLocalAsync(int codLocalidade) {
            this.RetornarVeiculosQueVaoChegarNoLocalAsync(codLocalidade, null);
        }
        
        /// <remarks/>
        public void RetornarVeiculosQueVaoChegarNoLocalAsync(int codLocalidade, object userState) {
            if ((this.RetornarVeiculosQueVaoChegarNoLocalOperationCompleted == null)) {
                this.RetornarVeiculosQueVaoChegarNoLocalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarVeiculosQueVaoChegarNoLocalOperationCompleted);
            }
            this.InvokeAsync("RetornarVeiculosQueVaoChegarNoLocal", new object[] {
                        codLocalidade}, this.RetornarVeiculosQueVaoChegarNoLocalOperationCompleted, userState);
        }
        
        private void OnRetornarVeiculosQueVaoChegarNoLocalOperationCompleted(object arg) {
            if ((this.RetornarVeiculosQueVaoChegarNoLocalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarVeiculosQueVaoChegarNoLocalCompleted(this, new RetornarVeiculosQueVaoChegarNoLocalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bgmrodotec.com.br/globus5/globus/SalvarRecebimentoSMS", RequestNamespace="http://bgmrodotec.com.br/globus5/globus", ResponseNamespace="http://bgmrodotec.com.br/globus5/globus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SalvarRecebimentoSMS(int id, string from, string to, string msg, System.DateTime dataHoraReceb) {
            this.Invoke("SalvarRecebimentoSMS", new object[] {
                        id,
                        from,
                        to,
                        msg,
                        dataHoraReceb});
        }
        
        /// <remarks/>
        public void SalvarRecebimentoSMSAsync(int id, string from, string to, string msg, System.DateTime dataHoraReceb) {
            this.SalvarRecebimentoSMSAsync(id, from, to, msg, dataHoraReceb, null);
        }
        
        /// <remarks/>
        public void SalvarRecebimentoSMSAsync(int id, string from, string to, string msg, System.DateTime dataHoraReceb, object userState) {
            if ((this.SalvarRecebimentoSMSOperationCompleted == null)) {
                this.SalvarRecebimentoSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalvarRecebimentoSMSOperationCompleted);
            }
            this.InvokeAsync("SalvarRecebimentoSMS", new object[] {
                        id,
                        from,
                        to,
                        msg,
                        dataHoraReceb}, this.SalvarRecebimentoSMSOperationCompleted, userState);
        }
        
        private void OnSalvarRecebimentoSMSOperationCompleted(object arg) {
            if ((this.SalvarRecebimentoSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalvarRecebimentoSMSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/globus5/globus")]
    public partial class sTabelaIntegradora {
        
        private int codOperadoraField;
        
        private int idOperadoraField;
        
        private int tipoDeteccaoField;
        
        private string descTipoDeteccaoField;
        
        private string localExternoField;
        
        private string veiculoExternoField;
        
        private string linhaExternoField;
        
        private string mensagemDeteccaoField;
        
        private System.DateTime dataOcorrenciaField;
        
        private int velocidadeField;
        
        private decimal latitudeField;
        
        private decimal longitudeField;
        
        private string codHorariaExternoField;
        
        private string codServicoExternoField;
        
        private string sentidoField;
        
        private int passageirosInField;
        
        private int passageirosOutField;
        
        private int passageirosCatracaField;
        
        private string codOcorrenciaExternoField;
        
        private string descOcorrenciaExternoField;
        
        private System.DateTime dataGravacaoField;
        
        private string codMotoristaExternoField;
        
        private string codCobradorExternoField;
        
        /// <remarks/>
        public int CodOperadora {
            get {
                return this.codOperadoraField;
            }
            set {
                this.codOperadoraField = value;
            }
        }
        
        /// <remarks/>
        public int IdOperadora {
            get {
                return this.idOperadoraField;
            }
            set {
                this.idOperadoraField = value;
            }
        }
        
        /// <remarks/>
        public int TipoDeteccao {
            get {
                return this.tipoDeteccaoField;
            }
            set {
                this.tipoDeteccaoField = value;
            }
        }
        
        /// <remarks/>
        public string DescTipoDeteccao {
            get {
                return this.descTipoDeteccaoField;
            }
            set {
                this.descTipoDeteccaoField = value;
            }
        }
        
        /// <remarks/>
        public string LocalExterno {
            get {
                return this.localExternoField;
            }
            set {
                this.localExternoField = value;
            }
        }
        
        /// <remarks/>
        public string VeiculoExterno {
            get {
                return this.veiculoExternoField;
            }
            set {
                this.veiculoExternoField = value;
            }
        }
        
        /// <remarks/>
        public string LinhaExterno {
            get {
                return this.linhaExternoField;
            }
            set {
                this.linhaExternoField = value;
            }
        }
        
        /// <remarks/>
        public string MensagemDeteccao {
            get {
                return this.mensagemDeteccaoField;
            }
            set {
                this.mensagemDeteccaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public int Velocidade {
            get {
                return this.velocidadeField;
            }
            set {
                this.velocidadeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string CodHorariaExterno {
            get {
                return this.codHorariaExternoField;
            }
            set {
                this.codHorariaExternoField = value;
            }
        }
        
        /// <remarks/>
        public string CodServicoExterno {
            get {
                return this.codServicoExternoField;
            }
            set {
                this.codServicoExternoField = value;
            }
        }
        
        /// <remarks/>
        public string Sentido {
            get {
                return this.sentidoField;
            }
            set {
                this.sentidoField = value;
            }
        }
        
        /// <remarks/>
        public int PassageirosIn {
            get {
                return this.passageirosInField;
            }
            set {
                this.passageirosInField = value;
            }
        }
        
        /// <remarks/>
        public int PassageirosOut {
            get {
                return this.passageirosOutField;
            }
            set {
                this.passageirosOutField = value;
            }
        }
        
        /// <remarks/>
        public int PassageirosCatraca {
            get {
                return this.passageirosCatracaField;
            }
            set {
                this.passageirosCatracaField = value;
            }
        }
        
        /// <remarks/>
        public string CodOcorrenciaExterno {
            get {
                return this.codOcorrenciaExternoField;
            }
            set {
                this.codOcorrenciaExternoField = value;
            }
        }
        
        /// <remarks/>
        public string DescOcorrenciaExterno {
            get {
                return this.descOcorrenciaExternoField;
            }
            set {
                this.descOcorrenciaExternoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataGravacao {
            get {
                return this.dataGravacaoField;
            }
            set {
                this.dataGravacaoField = value;
            }
        }
        
        /// <remarks/>
        public string CodMotoristaExterno {
            get {
                return this.codMotoristaExternoField;
            }
            set {
                this.codMotoristaExternoField = value;
            }
        }
        
        /// <remarks/>
        public string CodCobradorExterno {
            get {
                return this.codCobradorExternoField;
            }
            set {
                this.codCobradorExternoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/globus5/globus")]
    public partial class sRetornoSMS {
        
        private string tempoPrevistoField;
        
        private string codigoLinhaField;
        
        private string nomeAbrevLinhaField;
        
        private string origemLinhaField;
        
        private string destinoLinhaField;
        
        private string sentidoField;
        
        /// <remarks/>
        public string TempoPrevisto {
            get {
                return this.tempoPrevistoField;
            }
            set {
                this.tempoPrevistoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoLinha {
            get {
                return this.codigoLinhaField;
            }
            set {
                this.codigoLinhaField = value;
            }
        }
        
        /// <remarks/>
        public string NomeAbrevLinha {
            get {
                return this.nomeAbrevLinhaField;
            }
            set {
                this.nomeAbrevLinhaField = value;
            }
        }
        
        /// <remarks/>
        public string OrigemLinha {
            get {
                return this.origemLinhaField;
            }
            set {
                this.origemLinhaField = value;
            }
        }
        
        /// <remarks/>
        public string DestinoLinha {
            get {
                return this.destinoLinhaField;
            }
            set {
                this.destinoLinhaField = value;
            }
        }
        
        /// <remarks/>
        public string Sentido {
            get {
                return this.sentidoField;
            }
            set {
                this.sentidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bgmrodotec.com.br/globus5/globus")]
    public partial class sMensagens {
        
        private string tipoField;
        
        private int grupoField;
        
        private int codigoField;
        
        private int iDMensagemField;
        
        private int iDMensagemRetornoField;
        
        private int iDOperadorField;
        
        private string prefixoField;
        
        private int iDEmpresaField;
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public int Grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
            }
        }
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public int IDMensagem {
            get {
                return this.iDMensagemField;
            }
            set {
                this.iDMensagemField = value;
            }
        }
        
        /// <remarks/>
        public int IDMensagemRetorno {
            get {
                return this.iDMensagemRetornoField;
            }
            set {
                this.iDMensagemRetornoField = value;
            }
        }
        
        /// <remarks/>
        public int IDOperador {
            get {
                return this.iDOperadorField;
            }
            set {
                this.iDOperadorField = value;
            }
        }
        
        /// <remarks/>
        public string Prefixo {
            get {
                return this.prefixoField;
            }
            set {
                this.prefixoField = value;
            }
        }
        
        /// <remarks/>
        public int IDEmpresa {
            get {
                return this.iDEmpresaField;
            }
            set {
                this.iDEmpresaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void SalvarOuAlterarListaTabelaIntegradoraCompletedEventHandler(object sender, SalvarOuAlterarListaTabelaIntegradoraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SalvarOuAlterarListaTabelaIntegradoraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SalvarOuAlterarListaTabelaIntegradoraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void RetornarMensagensProDataCompletedEventHandler(object sender, RetornarMensagensProDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarMensagensProDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarMensagensProDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sMensagens[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sMensagens[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void SalvarMensagensProDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void RetornarVeiculosQueVaoChegarNoLocalDaLinhaCompletedEventHandler(object sender, RetornarVeiculosQueVaoChegarNoLocalDaLinhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarVeiculosQueVaoChegarNoLocalDaLinhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarVeiculosQueVaoChegarNoLocalDaLinhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sRetornoSMS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sRetornoSMS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void RetornarVeiculosQueVaoChegarNoLocalCompletedEventHandler(object sender, RetornarVeiculosQueVaoChegarNoLocalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarVeiculosQueVaoChegarNoLocalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarVeiculosQueVaoChegarNoLocalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sRetornoSMS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sRetornoSMS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void SalvarRecebimentoSMSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591