//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TBarGenAddin.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TBARGENADDIN_DIALOG         102
#define IDD_MAGDIALOG                   103
#define IDR_MAINFRAME                   128
#define IDR_MENU_POPUP                  136
#define IDR_TOOLBAR1                    138
#define IDD_DIALOG_OPTIONS              142
#define IDR_TOOLBAR_PREVIEW             151
#define IDR_MAINFRAME_TC                153
#define IDR_MAINFRAME_GR                154
#define IDR_ACCELERATORS                159
#define IDD_DIALOG_NEWTOOLBAR           160
#define IDD_DIALOG_HELP                 162
#define IDR_MAINFRAME_HT                164
#define IDB_BITMAP_TBHELPER             168
#define IDB_BITMAP_TBHELPER_GR          169
#define IDB_BITMAP_TBHELPER_HT          170
#define IDB_BITMAP_TBHELPER_TC          171
#define IDD_DIALOG_CHECK                172
#define IDR_MENUTOOLBARHELPER           173
#define IDD_DIALOG_LIBPREVIEW           183
#define IDB_BITMAP_FOLDER16             185
#define IDB_BITMAP2                     186
#define IDB_BITMAP_FOLDER32             186
#define IDC_LIST_BUTTONS                1000
#define IDC_BUTTON_OPENPROJECT          1001
#define IDC_BUTTON_SCANRESOURCE         1001
#define IDC_EDIT_RESOURCENAME           1002
#define IDC_BUTTON_TOP                  1003
#define IDC_BUTTON_UP                   1004
#define IDC_BUTTON_DOWN                 1005
#define IDC_BUTTON_BOTTOM               1006
#define IDC_BUTTON_REFRESH              1007
#define IDC_LIST_LIBRARY                1008
#define IDC_STATIC_TOOLBAR2             1009
#define IDC_STATIC_TOOLBAR              1009
#define IDC_BUTTON_COLOR                1010
#define IDC_STATIC_PICTURE              1011
#define IDC_EDIT_BMPFILE                1012
#define IDC_BUTTON_SAVEAS               1013
#define IDC_BUTTON_GENERATE             1014
#define IDC_BUTTON_SAVE                 1015
#define IDC_COMBO_BPP                   1016
#define IDC_CHECK_TCBMP                 1017
#define IDC_CHECK_GRBMP                 1018
#define IDC_BUTTON_TCOPT                1019
#define IDC_BUTTON_GROPT2               1020
#define IDC_BUTTON_GROPT                1020
#define IDC_COMBO_RESOURCENAME          1021
#define IDC_BUTTON_APPLY                1022
#define IDC_BUTTON_TCOPT2               1022
#define IDC_BUTTON_HTOPT                1022
#define IDC_BUTTON_CANCEL               1023
#define IDC_BUTTON_MASKCOLOR            1023
#define IDC_CHECK_REPLACEOF             1024
#define IDC_EDIT_TEMPF                  1025
#define IDC_BUTTON_BRWTEMP              1026
#define IDC_CHECK_AUTORESIZE            1027
#define IDC_EDIT_IMAGE_LIB              1028
#define IDC_BUTTON_BRWIMGLIB            1029
#define IDC_STATIC_IMGLIB               1029
#define IDC_BUTTON_ADDFILE              1030
#define IDC_STATIC_LINK                 1031
#define IDC_BUTTON_ADDFILE2             1031
#define IDC_BUTTON_DELFILE              1031
#define IDC_LIST_IDFILE                 1032
#define IDC_EDIT1                       1034
#define IDC_EDIT_TID                    1034
#define IDC_EDIT_TEXT                   1034
#define IDC_EDIT_ERX                    1034
#define IDC_EDIT_RX                     1035
#define IDC_EDIT_ERY                    1035
#define IDC_EDIT_RY                     1036
#define IDC_COMBO_VCTYPE                1037
#define IDC_CHECK_HTBMP                 1038
#define IDC_SPIN_MRUSIZE                1040
#define IDC_STATIC_MRUSIZE              1041
#define IDC_STATIC_CNT                  1042
#define IDC_SPIN_CNT                    1043
#define IDC_STATIC_MSG                  1044
#define IDC_STATIC_LINKFORUM            1046
#define IDC_LIST_LIBPREVIEW             1047
#define IDC_BUTTON_TEST                 1048
#define IDC_COMBO_ICONSIZE              1049
#define IDC_CHECK_ACTSIZE               1051
#define IDC_CHECK_FILTERSIZE            1052
#define IDC_CHECK_RPTVIEW               1053
#define IDC_CHECK_MASKCORNER            1054
#define IDC_CHECK_MASKBUTTON            1055
#define IDC_STATIC_TEXT                 1055
#define ID__ADDNEW                      32773
#define ID__DELETE                      32774
#define ID__RESIZEIMAGE                 32775
#define ID_POPUP_EDITIMAGE              32776
#define ID_POPUP_DELETE                 32778
#define ID_EDITIMAGE_RESIZE             32779
#define ID_EDITIMAGE_ROTATE             32780
#define ID_POPUP_ADDNEW                 32781
#define ID_FILE_SAVEBITMAP              32783
#define ID_FILE_GENRATETOOLBAR          32784
#define ID_IMAGE_RESIZE                 32785
#define ID_IMAGE_ROTATE                 32786
#define ID_TOOLS_OPTIONS                32787
#define ID_ABOUT_ABOUTTBARGENADDIN      32788
#define ID_FILE_EXIT                    32789
#define ID_BUTTON32790                  32790
#define ID_BUTTON32791                  32791
#define IDR_BUTTON_WARNING              32794
#define ID_BUTTON_RESIZE                32803
#define ID_BUTTON_ROTATE                32804
#define IDR_BUTTON_INFORM1              32805
#define ID_ACCELERATOR_CANC             32807
#define ID_ACCELERATOR_REFRESH          32818
#define ID_TOOLS_COPYTOOLBARTOCLIPBOARD 32823
#define ID_TOOLS_MERGEIDWITHPROJECT     32824
#define ID_POPUP_INSERTNEW              32825
#define ID_Menu                         32830
#define ID_FILE_MRU                     32831
#define ID_RECENTFILE_J                 32832
#define ID_FILE_RECENTFILE              32833
#define ID_TOOLS_TOOLBAR                32834
#define ID_TOOLBAR_COPYTOCLIPBOARD      32835
#define ID_TOOLBAR_MERGEIDS             32836
#define ID_ABOUT_HELP                   32839
#define ID_ACCELERATOR_HELP             -32696
#define ID_TOOLBAR_GENERATE             32842
#define ID_BUTTON_PLUS                  32844
#define ID_BUTTON_INDENT2               32845
#define ID_BUTTON_MINUS                 32846
#define ID_ABOUT_CHECKFORUPDATES        32858
#define ID_POPUP_SAVEIMAGEINLIBRARY     32859

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        188
#define _APS_NEXT_COMMAND_VALUE         32862
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
