//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace client.SecureServiceProxy {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public class Service1Wse : Microsoft.Web.Services2.WebServicesClientProtocol {
        
        /// <remarks/>
        public Service1Wse() {
            this.Url = "http://hydhtc35369/kerberos/service/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/perform", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long perform(long a, long b) {
            object[] results = this.Invoke("perform", new object[] {
                        a,
                        b});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginperform(long a, long b, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("perform", new object[] {
                        a,
                        b}, callback, asyncState);
        }
        
        /// <remarks/>
        public long Endperform(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://hydhtc35369/kerberos/service/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/perform", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long perform(long a, long b) {
            object[] results = this.Invoke("perform", new object[] {
                        a,
                        b});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginperform(long a, long b, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("perform", new object[] {
                        a,
                        b}, callback, asyncState);
        }
        
        /// <remarks/>
        public long Endperform(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
    }
}
