//=============================================================================
// System  : Sandcastle Help File Builder Utilities
// File    : BuildStepEnum.cs
// Author  : Eric Woodruff
// Updated : 02/21/2007
// Note    : Copyright 2006-2007, Eric Woodruff, All rights reserved
// Compiler: Microsoft Visual C#
//
// This file contains the enumerated type that defines the build steps used
// when reporting progress during a build.
//
// This code may be used in compiled form in any way you desire.  This file
// may be redistributed unmodified by any means PROVIDING it is not sold for
// profit without the author's written consent, and providing that this notice
// and the author's name and all copyright notices remain intact.
//
// This code is provided "as is" with no warranty either express or implied.
// The author accepts no liability for any damage or loss of business that
// this product may cause.
//
// Version     Date     Who  Comments
// ============================================================================
// 1.0.0.0  08/10/2006  EFW  Created the code
//=============================================================================

using System;

namespace SandcastleBuilder.Utils
{
    /// <summary>
    /// This public enumerated type defines the build steps used when reporting
    /// progress during a build.
    /// </summary>
    [Serializable]
    public enum BuildStep
    {
        /// <summary>The build has not yet started.</summary>
        None,
        /// <summary>Initializing to prepare for build.</summary>
        Initializing,
        /// <summary>The working folder is about to be created or cleared.</summary>
        ClearWorkFolder,
        /// <summary>The builder is searching for Sandcastle and the
        /// HTML help compiler.</summary>
        FindingTools,
        /// <summary>The documentation assembly information is being validated.</summary>
        ValidatingAssemblies,
        /// <summary>The <b>sandcastle.config</b> file is being created.</summary>
        CreateConfig,
        /// <summary>The document assembly dependencies are being copied.</summary>
        CopyDependencies,
        /// <summary>The shared content files are being generated.</summary>
        GenerateSharedContent,
        /// <summary>The reflection information is being generated by
        /// <b>MRefBuilder</b>.</summary>
        GenerateReflectionInfo,
        /// <summary>Duplicate topic information is being purged from the
        /// reflection information file.</summary>
        PurgeDuplicateTopics,
        /// <summary>The Visibility category properties are being applied to
        /// the reflection information file to remove unwanted items.</summary>
        ApplyVisibilityProperties,
        /// <summary>Namespace summary information is being generated.</summary>
        GenerateNamespaceSummaries,
        /// <summary>The reflection information is being transformed by
        /// <b>XslTransform</b>.</summary>
        TransformReflectionInfo,
        /// <summary>Help topic filenames are being altered.</summary>
        ModifyHelpTopicFilenames,
        /// <summary>The standard help file content (art, scripts, and styles)
        /// is being copied to the help project folder.</summary>
        CopyStandardContent,
        /// <summary>The additional content files are being copied to the
        /// help project folder.</summary>
        CopyAdditionalContent,
        /// <summary>Help file topics are being generated by
        /// <b>BuildAssembler</b>.</summary>
        BuildHelpTopics,
        /// <summary>The table of content is being generated by
        /// <b>XslTransform</b>.</summary>
        GenerateTableOfContent,
        /// <summary>The table of content is being updated with additional
        /// content items and the default page is being determined.</summary>
        UpdateTableOfContent,
        /// <summary>The help file index is being generated.</summary>
        GenerateHelpFileIndex,
        /// <summary>The help project file is being generated.</summary>
        GenerateHelpProject,
        /// <summary>The help file project is being compiled.</summary>
        CompilingHelpFile,
        /// <summary>The website files are being copied to the output path.</summary>
        CopyingWebsiteFiles,
        /// <summary>The temporary help project files are being removed.</summary>
        CleanIntermediates,
        /// <summary>The build has completed successfully.</summary>
        Completed,
        /// <summary>The build was canceled by user request.</summary>
        Canceled,
        /// <summary>The build failed with an unexpected error.</summary>
        Failed
    }
}
